twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    date:
        timezone: Europe/Minsk
        format: d.m.Y
    form_themes:
        - bootstrap_4_layout.html.twig