version: '2'

services:

  app:
    container_name: ds.app
    build: docker/php
    volumes:
      - .:/var/www
    ports:
      - 9000
    environment:
      - DOCKER_IP=${DOCKER_IP}

  nginx:
    container_name: ds.nginx
    build: docker/nginx
    volumes_from:
      - app
    ports:
      - 834:80

  db:
    container_name: ds.mysql
    image: mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    volumes:
      - ./docker/mysql/.db:/var/lib/mysql
    volumes_from:
      - app
    env_file:
      - ./docker/mysql/.env
    ports:
        - 849:3306
