version: '2'

services:

  app:
    container_name: sf.app
    build: docker/php
    volumes:
      - .:/app

  nginx:
    container_name: sf.nginx
    build: docker/nginx
    volumes_from:
      - app
    ports:
      - 834:80

  db:
    container_name: sf.mysql
    image: mysql
    volumes:
      - ./docker/mysql/.db:/var/lib/mysql
    env_file:
      - ./docker/mysql/.env
    ports:
        - 849:3306

  phpmyadmin:
    container_name: sf.phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
        - 863:80
