<?php

namespace ParserBundle\Repository;

use ParserBundle\Entity\Source;

/**
 * SourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @var int|null $results
     * @return array
     */
    public function findNextSources($results = null)
    {
        return $this->createQueryBuilder('sourse')
            ->orderBy('sourse.updatedAt')
            ->setMaxResults($results)
            ->getQuery()
            ->getResult();
    }
}
