core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: '@ApiBundle/Controller/'
    type: annotation

rssatom:
    resource: "@DebrilRssAtomBundle/Resources/config/routing.yml"
