<?php

namespace App\ParserBundle\Repository;

use ParserBundle\Entity\Source;

/**
 * SourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @var int|null $results
     * @return array
     */
    public function findForUpdate($results = null)
    {
        return $this->createQueryBuilder('sourse')
            ->where('sourse.updateOn <= :now')
            ->setParameter('now', new \DateTime())
            ->orWhere('sourse.updateOn is null')
            ->orderBy('sourse.updateOn')
            ->setMaxResults($results)
            ->getQuery()
            ->getResult();
    }
}
