<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\Item;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findLast()
    {
        return $this->createQueryBuilder('i')
            //->select(['i.title', 'i.link'])
            ->leftJoin('i.source', 's')
            ->addSelect('s')
            ->orderBy('i.publishedAt','DESC')
            ->setMaxResults(60)
            ->getQuery()
            ->getArrayResult();
    }

    /**
     * @return array
     */
    public function findByTagId($id)
    {
        return $this->createQueryBuilder('i')
            ->leftJoin('i.source', 's')
            ->leftJoin('s.tags', 't')
            ->addSelect('s')
            ->where('t.id = :tag_id')
            ->setParameter('tag_id', $id)
            ->orderBy('i.   publishedAt', 'DESC')
            ->setMaxResults(60)
            ->getQuery()
            ->getArrayResult();
    }
}
