<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\Item;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findLast()
    {
        return $this->createQueryBuilder('i')
            ->select(['i.title', 'i.link'])
            ->orderBy('i.publishedAt','DESC')
            ->setMaxResults(10)
            ->getQuery()
            ->getArrayResult();
    }
}
