<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\Item;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteAll()
    {
        $queryBuilder = $this->createQueryBuilder(Item::class)
            ->delete();
        return $queryBuilder->getQuery()->execute();
    }
}
